POST https://vkpns.rustore.ru/v1/projects/OClMKCDhoBtj3kZ5YAkjmF1BBytBtWEX/messages:send HTTP/2
Content-Type: application/json
Authorization: Bearer {{bearer}}

{
   "message":{
      "token": "{{token}}",
      "notification":{
        "body":"This is an rustore notification2!",
        "title":"Message",
        "image":"https://image-hosting.org/284239234.jpeg"
      }
   }
}
