POST https://vkpns.rustore.ru/v1/projects/myproject-b5ae1/messages:send HTTP/2
Content-Type: application/json
Authorization: Bearer cBFCn...

{
   "message":{
      "token":"cBFCn-fLIdRA2qXRuCnNq-49GYHFpsK5Y62lQX4QUIFUxSVqQ68vkCQh2YA-92jL",
      "notification":{
        "body":"This is an notification message!",
        "title":"Message",
        "image":"https://image-hosting.org/284239234.jpeg"
      }
   }
}
