// Autogenerated from Pigeon (v4.2.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package ru.rustore.flutter_rustore_push.pigeons;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Rustore {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class Message {
    private @Nullable String messageId;
    public @Nullable String getMessageId() { return messageId; }
    public void setMessageId(@Nullable String setterArg) {
      this.messageId = setterArg;
    }

    private @NonNull Long priority;
    public @NonNull Long getPriority() { return priority; }
    public void setPriority(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"priority\" is null.");
      }
      this.priority = setterArg;
    }

    private @NonNull Long ttl;
    public @NonNull Long getTtl() { return ttl; }
    public void setTtl(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"ttl\" is null.");
      }
      this.ttl = setterArg;
    }

    private @Nullable String collapseKey;
    public @Nullable String getCollapseKey() { return collapseKey; }
    public void setCollapseKey(@Nullable String setterArg) {
      this.collapseKey = setterArg;
    }

    private @NonNull Map<String, String> data;
    public @NonNull Map<String, String> getData() { return data; }
    public void setData(@NonNull Map<String, String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"data\" is null.");
      }
      this.data = setterArg;
    }

    private @Nullable Notification notification;
    public @Nullable Notification getNotification() { return notification; }
    public void setNotification(@Nullable Notification setterArg) {
      this.notification = setterArg;
    }

    /**Constructor is private to enforce null safety; use Builder. */
    private Message() {}
    public static final class Builder {
      private @Nullable String messageId;
      public @NonNull Builder setMessageId(@Nullable String setterArg) {
        this.messageId = setterArg;
        return this;
      }
      private @Nullable Long priority;
      public @NonNull Builder setPriority(@NonNull Long setterArg) {
        this.priority = setterArg;
        return this;
      }
      private @Nullable Long ttl;
      public @NonNull Builder setTtl(@NonNull Long setterArg) {
        this.ttl = setterArg;
        return this;
      }
      private @Nullable String collapseKey;
      public @NonNull Builder setCollapseKey(@Nullable String setterArg) {
        this.collapseKey = setterArg;
        return this;
      }
      private @Nullable Map<String, String> data;
      public @NonNull Builder setData(@NonNull Map<String, String> setterArg) {
        this.data = setterArg;
        return this;
      }
      private @Nullable Notification notification;
      public @NonNull Builder setNotification(@Nullable Notification setterArg) {
        this.notification = setterArg;
        return this;
      }
      public @NonNull Message build() {
        Message pigeonReturn = new Message();
        pigeonReturn.setMessageId(messageId);
        pigeonReturn.setPriority(priority);
        pigeonReturn.setTtl(ttl);
        pigeonReturn.setCollapseKey(collapseKey);
        pigeonReturn.setData(data);
        pigeonReturn.setNotification(notification);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(6);
      toListResult.add(messageId);
      toListResult.add(priority);
      toListResult.add(ttl);
      toListResult.add(collapseKey);
      toListResult.add(data);
      toListResult.add((notification == null) ? null : notification.toList());
      return toListResult;
    }
    static @NonNull Message fromList(@NonNull ArrayList<Object> list) {
      Message pigeonResult = new Message();
      Object messageId = list.get(0);
      pigeonResult.setMessageId((String)messageId);
      Object priority = list.get(1);
      pigeonResult.setPriority((priority == null) ? null : ((priority instanceof Integer) ? (Integer)priority : (Long)priority));
      Object ttl = list.get(2);
      pigeonResult.setTtl((ttl == null) ? null : ((ttl instanceof Integer) ? (Integer)ttl : (Long)ttl));
      Object collapseKey = list.get(3);
      pigeonResult.setCollapseKey((String)collapseKey);
      Object data = list.get(4);
      pigeonResult.setData((Map<String, String>)data);
      Object notification = list.get(5);
      pigeonResult.setNotification((notification == null) ? null : Notification.fromList((ArrayList<Object>)notification));
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class Notification {
    private @Nullable String title;
    public @Nullable String getTitle() { return title; }
    public void setTitle(@Nullable String setterArg) {
      this.title = setterArg;
    }

    private @Nullable String body;
    public @Nullable String getBody() { return body; }
    public void setBody(@Nullable String setterArg) {
      this.body = setterArg;
    }

    private @Nullable String channelId;
    public @Nullable String getChannelId() { return channelId; }
    public void setChannelId(@Nullable String setterArg) {
      this.channelId = setterArg;
    }

    private @Nullable String imageUrl;
    public @Nullable String getImageUrl() { return imageUrl; }
    public void setImageUrl(@Nullable String setterArg) {
      this.imageUrl = setterArg;
    }

    private @Nullable String color;
    public @Nullable String getColor() { return color; }
    public void setColor(@Nullable String setterArg) {
      this.color = setterArg;
    }

    private @Nullable String icon;
    public @Nullable String getIcon() { return icon; }
    public void setIcon(@Nullable String setterArg) {
      this.icon = setterArg;
    }

    private @Nullable String clickAction;
    public @Nullable String getClickAction() { return clickAction; }
    public void setClickAction(@Nullable String setterArg) {
      this.clickAction = setterArg;
    }

    public static final class Builder {
      private @Nullable String title;
      public @NonNull Builder setTitle(@Nullable String setterArg) {
        this.title = setterArg;
        return this;
      }
      private @Nullable String body;
      public @NonNull Builder setBody(@Nullable String setterArg) {
        this.body = setterArg;
        return this;
      }
      private @Nullable String channelId;
      public @NonNull Builder setChannelId(@Nullable String setterArg) {
        this.channelId = setterArg;
        return this;
      }
      private @Nullable String imageUrl;
      public @NonNull Builder setImageUrl(@Nullable String setterArg) {
        this.imageUrl = setterArg;
        return this;
      }
      private @Nullable String color;
      public @NonNull Builder setColor(@Nullable String setterArg) {
        this.color = setterArg;
        return this;
      }
      private @Nullable String icon;
      public @NonNull Builder setIcon(@Nullable String setterArg) {
        this.icon = setterArg;
        return this;
      }
      private @Nullable String clickAction;
      public @NonNull Builder setClickAction(@Nullable String setterArg) {
        this.clickAction = setterArg;
        return this;
      }
      public @NonNull Notification build() {
        Notification pigeonReturn = new Notification();
        pigeonReturn.setTitle(title);
        pigeonReturn.setBody(body);
        pigeonReturn.setChannelId(channelId);
        pigeonReturn.setImageUrl(imageUrl);
        pigeonReturn.setColor(color);
        pigeonReturn.setIcon(icon);
        pigeonReturn.setClickAction(clickAction);
        return pigeonReturn;
      }
    }
    @NonNull ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(7);
      toListResult.add(title);
      toListResult.add(body);
      toListResult.add(channelId);
      toListResult.add(imageUrl);
      toListResult.add(color);
      toListResult.add(icon);
      toListResult.add(clickAction);
      return toListResult;
    }
    static @NonNull Notification fromList(@NonNull ArrayList<Object> list) {
      Notification pigeonResult = new Notification();
      Object title = list.get(0);
      pigeonResult.setTitle((String)title);
      Object body = list.get(1);
      pigeonResult.setBody((String)body);
      Object channelId = list.get(2);
      pigeonResult.setChannelId((String)channelId);
      Object imageUrl = list.get(3);
      pigeonResult.setImageUrl((String)imageUrl);
      Object color = list.get(4);
      pigeonResult.setColor((String)color);
      Object icon = list.get(5);
      pigeonResult.setIcon((String)icon);
      Object clickAction = list.get(6);
      pigeonResult.setClickAction((String)clickAction);
      return pigeonResult;
    }
  }

  public interface Result<T> {
    void success(T result);
    void error(Throwable error);
  }
  private static class RustorePushCodec extends StandardMessageCodec {
    public static final RustorePushCodec INSTANCE = new RustorePushCodec();
    private RustorePushCodec() {}
    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return Message.fromList((ArrayList<Object>) readValue(buffer));
        
        case (byte)129:         
          return Notification.fromList((ArrayList<Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value)     {
      if (value instanceof Message) {
        stream.write(128);
        writeValue(stream, ((Message) value).toList());
      } else 
      if (value instanceof Notification) {
        stream.write(129);
        writeValue(stream, ((Notification) value).toList());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface RustorePush {
    void available(Result<Boolean> result);
    void onNewToken(Result<String> result);
    void onMessageReceived(Result<Message> result);
    void onDeletedMessages(Result<Void> result);
    void onError(Result<String> result);
    void getToken(Result<String> result);
    void deleteToken(Result<Void> result);

    /** The codec used by RustorePush. */
    static MessageCodec<Object> getCodec() {
      return       RustorePushCodec.INSTANCE;    }
    /**Sets up an instance of `RustorePush` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, RustorePush api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.available", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<Boolean> resultCallback = new Result<Boolean>() {
                public void success(Boolean result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.available(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.onNewToken", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<String> resultCallback = new Result<String>() {
                public void success(String result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.onNewToken(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.onMessageReceived", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<Message> resultCallback = new Result<Message>() {
                public void success(Message result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.onMessageReceived(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.onDeletedMessages", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.add(0, null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.onDeletedMessages(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.onError", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<String> resultCallback = new Result<String>() {
                public void success(String result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.onError(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.getToken", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<String> resultCallback = new Result<String>() {
                public void success(String result) {
                  wrapped.add(0, result);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.getToken(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.RustorePush.deleteToken", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            ArrayList wrapped = new ArrayList<>();
            try {
              Result<Void> resultCallback = new Result<Void>() {
                public void success(Void result) {
                  wrapped.add(0, null);
                  reply.reply(wrapped);
                }
                public void error(Throwable error) {
                  ArrayList<Object> wrappedError = wrapError(error);
                  reply.reply(wrappedError);
                }
              };

              api.deleteToken(resultCallback);
            }
            catch (Error | RuntimeException exception) {
              ArrayList<Object> wrappedError = wrapError(exception);
              reply.reply(wrappedError);
            }
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  @NonNull private static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    errorList.add(exception.toString());
    errorList.add(exception.getClass().getSimpleName());
    errorList.add("Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorList;
  }
}
